apiVersion: batch/v1
kind: CronJob
metadata:
  name: spring-batch-demo
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spring-batch-demo
            image: localhost:5000/spring-batch-demo:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure